[tool.ruff]
line-length = 88
exclude = ["migrations/versions"]


[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]
strict = true

[tool.djlint]
profile = "jinja"
indent = 2
preserve_blank_lines = true